### ISSUE TITLE
Config: Validate worker address from the facilitator-config.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#10]
This is an implementation ticket. The actual implementation may vary as we start working on it.
Please check #2 first for interface and any updates in params.

Worker address provided in the config must be validated so that they can be used for facilitation.
- Get the worker address for each chain
- Validate if encrypted_account for the address is available.
- Validate if the password is available in the env variable. The env variable name will be in the following format `MOSAIC_ADDRESS_PASSW_<address>`
- Validate if we can unlock the account and have access to the private key.

**Comment by abhayks1** [comment]
Moving this to Backlog as my current ticket #50 is unblocked with test setup #72.
I haven't made much progress on this ticket.

**Comment by puneet-khushwani-eth** [comment]
I guess this ticket has quite an overlap with Issue [33](https://github.com/OpenST/facilitator/issues/33)

As @pgev has already started implementation on the above one, I would suggest to reuse the code he pushes in for this.

**Comment by deepesh-kn** [comment]
Closing this ticket, as the unlock worker address is already handled.
