### ISSUE TITLE
Config: Parse facilitator-config json file to populate the config variables.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#11]
This is an implementation ticket. The actual implementation may vary as we start working on it.
Please check #2 first for the interface.

Config provides an easy way to read the config from `mosaic-config` and `facilitation-config`

- #2 will define the properties that are exposed from the config.
- This issue is about parsing the facilitator config JSON file and populate the class variables.

**Comment by gulshanvasnani** [comment]
This ticket's solution is available at PR https://github.com/OpenST/facilitator/pull/65

**Comment by deepesh-kn** [comment]
Closing this as its already handled in #65
