### ISSUE TITLE
Define the interfaces for all the functions in Config

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#2]
Config provides all the data that is needed to run the facilitator. It reads data from `mosaic-config` and `facilitator-config` JSON files and provides getter functions that can be used in other parts of the facilitator code base.

# **This ticket is about defining the interfaces of all the functions in the Config.**

The proposed functions are provided for reference. 
The implementer can think this in detail and can add/remove functions.

- [ ] **constructor**
	 - Accepts `mosaic-config` and `facilitator-config` as params
	 - Validates `config` (against schema for `facilitator-config : mosaic-config`)
	 - Validate worker addresses
<br/>
<br/>

- [ ] **function to get DB path.**
[Check DB tickets if more functions related to DB are needed]
<br/>

- [ ] **function to get RPC endpoints for the given chain.**
<br/>

- [ ] **function to get all the worker addresses for the given chain.**
<br/>

- [ ] **function to get `encrypted_account` for a given address.**
<br/>

- [ ] **function to get OSTComposer contract address**
<br/>

- [ ] **function to get all Gateway contract addresses.**
<br/>

- [ ] **function to get Gateway contract address for a given chain.**
<br/>

- [ ] **function to get CoGateway contract address for a given chain.**
<br/>

- [ ] **function to get worker addresses for a given chain.**
<br/>

________________
**Example of mosaic-config.json is given below.**

```
{
  "originChain": {
    "chainId": 3,
    "contractAddresses": { // Contracts deployed on origin chain, should be reused for all auxiliary chains. 
      "simpleTokenAddress": "",
      "merklePatriciaLibAddress": "",
      "GatewayLibAddress": "",
      "messageBusAddress": ""
    }
  },
  "auxiliaryChains": {
    "1406": {
      "chainId": 1406,
      "bootNodes": [], //List of boot nodes
      "genesis": {}, 
      "contractAddresses": { // Contract addresses specific to single auxiliary chain 
        "origin": { // Contracts deployed on origin chain specific to single auxiliary chain
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": "",
          "ostComposerAddress": "" 
        },
        "auxiliary": { // Contracts deployed on the auxiliary chain
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      }
    },
    "1407": {
      "chainId": 1407,
      "bootNodes": [], //List of boot nodes
      "genesis": {},
      "contractAddresses": { // Contract addresses specific to single auxiliary chain 
        "origin": { // Contracts deployed on origin chain specific to single auxiliary chain
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": "",
          "ostComposerAddress": ""
        },
        "auxiliary": { // Contracts deployed on the auxiliary chain
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      }
    }
  }
}
```
________________
**Example of facilitator-config.json is given below.**
```
{
    "db": {
            "db_path": "<db_path>",
            // other params
    },
    "chains": {
        <chain_id_1>: {
                   "rpc": "http://localhost:3000",
                   "workers": [0xaddress1, 0xaddress2],
		},
	<chain_id_2>: {
                  "rpc": "http://localhost:4000",
                  "workers": [0xaddress3, 0xaddress4]
		}	
	}
    "encrypted_accounts": {
        "0xaddress1": {
        
        },
        "0xaddress2": {
        
        },
        "0xaddress3": {
        
        },
        ,
        "0xaddress4": {
        
        }
    }
}
```

**Comment by benjaminbollen** [comment]
validate mosaic-config, also does on-chain checks?

**Comment by benjaminbollen** [comment]
answer: mosaic-config will have mandatory fields (entry points into contract constellation) and optional fields that can be filled out by querying the contracts and reading the links (eg. Organization address);  Mosaic-chains will have a verifier functionality to assert and fill out the optional config fields

**Comment by benjaminbollen** [comment]
i updated the ticket description to remove the `validation` functions from the interface; the constructor should fail if the schema is not matched correctly

**Comment by abhayks1** [comment]
Just a note Config.ts can change based on learnings of below ticket:
https://github.com/OpenST/facilitator/issues/50
