### ISSUE TITLE
DB Setup

### ISSUE THREAD

**Issue by abhayks1** [OpenST/facilitator#42]
The ticket is about setting up DB and defining npm to interact with the databases tables.

- Setup **docker+<strike>mysql</strike> sqlite**. If we decide to chose any other database, update the docker accordingly.

- Use a good javascript npm/library for interacting with database. Below npm can be used. It also supports migration.
  http://docs.sequelizejs.com/

Acceptance criteria of the ticket is to run a sqlite <strike>mysql</strike> node and connect it with nodejs npm.

**Comment by deepesh-kn** [comment]
- Select latest and stable version for docker sqlite image
- Define docker compose.yml for sqlite.
- Update package.json with appropriate (sqlite) npm package.
- On terminal test the connections. (or dummy table updates.)

**Comment by pgev** [comment]
https://www.npmjs.com/package/sqlite

**Comment by pgev** [comment]
https://www.npmjs.com/package/@types/sqlite3
