### ISSUE TITLE
Commander : Facilitator Stop command

### ISSUE THREAD

**Issue by gulshanvasnani** [OpenST/facilitator#43]
These are the commands that can be used to run the facilitators.

The proposed command is as given below, the implementer can improvise this.

- [ ] **Stop command**.

```
./facilitator stop  --chainid <chainId> 

```

- The facilitator can be stopped by `./facilitator stop`.
- `chainid` is the chainid value to be stopped. 

<br/>

- [ ] **Help command**.
```
./facilitator --help

```
- This command provides help for the facilitator command.

**Comment by deepesh-kn** [comment]
Closing this ticket as stop command is not needed.
