### ISSUE TITLE
Commander: Facilitator list

### ISSUE THREAD

**Issue by gulshanvasnani** [OpenST/facilitator#45]
The proposed command is as given below, the implementer can improvise this.

- [ ] **List command**.

```
./facilitator list 
```

- The facilitator's which are started can be listed by `./facilitator list` command.
<br/>

- [ ] **Help command**.
```
./facilitator --help

```
- This command provides help for the facilitator command.

**Comment by deepesh-kn** [comment]
Closing is as it is not required.
