### ISSUE TITLE
DB: Implement StakeRequest model

### ISSUE THREAD

**Issue by abhayks1** [OpenST/facilitator#47]
The ticket is about implementation of **StakeRequest** model.

- Create folder models.

- Create class StakeRequest inside models directory which will interact with stake_requests table.

- All model classes which interacts with database tables should be put in models directory.

- Create script to create stake_requests table. SequelJS has good support for migrations. https://sequelize.readthedocs.io/en/latest/docs/migrations/

StakeRequest model stores stake requests information and their processing status. Below is the proposed schema of stake_requests table. 

Note: _This will give a rough idea, the schema can be improved by the implementer._ 
```
name | type | references | description
-- | -- | -- | --
"id" | INTEGER |   | Primary Key
"stake_request_hash" | VARCHAR |   | Unique Key.
"message_hash" | VARCHAR |   |  
"origin_chain_id" | INTEGER |   |  
"aux_chain_id" | INTEGER |   |  
"gateway_address" | VARCHAR |   |  
"origin_worker_address" | VARCHAR |   |  
"auxiliary_worker_address" | VARCHAR |   |  
"hash_lock" | VARCHAR |   |  
"unlock_secret" | VARCHAR |   |  
"status" | INTEGER |   | 
"created_at" | DATETIME |  | Time when the record was created
"updated_at" | DATETIME | | Time when worker completed it's process 
```

Proposed STATUS Values (Add/Remove if needed)

REQUESTED
ACCEPTED
ACCEPTED_FAILED
ACCOUNT_PROVEN
ACCOUNT_PROVEN_FAILED
STAKE_INTENT_CONFIRMED
STAKE_INTENT_CONFIRMED_FAILED
PROGRESS_STAKE
PROGRESS_STAKE_FAILED
PROGRESS_MINT_COMPLETE
PROGRESS_MINT_FAILED
UNKNOWN

StakeRequest model should define methods for below use cases:

- Define status enum values. 

- Method to fetch stake requests waiting for processing and mark them as in progress. After fetching the pending stake requests, update worker address(auxiliary or origin), updated_at in the table. We can process the requests in batches also. 

- Method to insert new entry for StakeRequested event in stake_requests table.

- Method to update the status, updated_at in stake_requests table for a given stake_request_hash.

**Comment by deepesh-kn** [comment]
- `status` will have status related to stake request.
    - REQUESTED
    - ACCEPTED
    - ACCEPTED_FAILED
    - REVOKED
    - REJECTED

We can have following 2 columns.
- `origin_message_status` 
- `auxiliary_message_status`

**Comment by deepesh-kn** [comment]
- Implement the state machine for `status`.
- Implement the state machine for `origin_message_status` and `auxiliary_message_status`.

**Comment by benjaminbollen** [comment]
for this scope exclude `revert` subsection of message status statemachine
