### ISSUE TITLE
Subscribe and unsubscribe to graph node instance.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#50]
Subscribe/Unsubscribe to all entities with one subscriber per graph-node instance (ie. per chain)

**Comment by abhayks1** [comment]
Moving this to Backlog as this ticket needs to be picked up after completing below ticket:
#5 "Define facilitator interfaces"

**Comment by abhayks1** [comment]
**Update on the ticket**

Discussed with thegraph team on Discord and they have recommended below client:
https://www.apollographql.com/docs/react/advanced/subscriptions/#client-setup

Below is the working code for query:

```
import ApolloClient from "apollo-boost";
import fetch from 'node-fetch';
import gql from 'graphql-tag'

const apolloClient = new ApolloClient({
  uri: "http://localhost:8000/subgraphs/name/openst/ost-composer",
  fetch: fetch,
});
apolloClient.query({query: gql`query{stakeRequesteds{id}}`}).then(result=>console.log(result));
```

Below is the working subscription code:

```
import ApolloClient from "apollo-client";
import { WebSocketLink } from 'apollo-link-ws';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { SubscriptionClient } from "subscriptions-transport-ws";
import gql from 'graphql-tag'
import ws = require('ws');

const subscriptionClient = new SubscriptionClient("ws://localhost:8001/subgraphs/name/openst/ost-composer", {
  reconnect: true
}, ws);

const link = new WebSocketLink(subscriptionClient);

const apolloClient = new ApolloClient({link: link, cache: new InMemoryCache()});
const subscriptionQry = 'subscription{stakeRequesteds(where:{ amount_gt: "9"}){id amount stakeRequestHash}}'
const gqlQry = gql`${subscriptionQry}`;
apolloClient.subscribe({query: gqlQry, variables: {}}).subscribe({next(output) {console.log(output.data);}});
```

With above subscription it returns all data matching the query for every new stakeRequested event. Ideally it should return only the incremental data. e.g. Should return only new stakeRequested event data.

I have also created hackmd doc with troubleshooting examples and learnings while integrating the client. Link: https://hackmd.io/mVF9i4B7S3O2Iq-Z_leFMg
