### ISSUE TITLE
Implement stake requests model class

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#53]
Implement stake requests model class

- stake_request_hash
- message_hash
- amount
- beneficiary
- gasPrice
- gasLimit
- nonce
- gateway
- staker_proxy (-> sender in gateway, for messagehash)

Abstract the database interaction layer.
(StakeRequestRepository, Query… etc remember the discussion)

**Comment by pgev** [comment]
In a draft PR (#66) DatabaseWrapper and StakeRequestRepository main classes are created. 

DatabaseWrapper gives a promisified interface to sqlite3.Database object to ease usage of database operations.
StakeRequestRepository enables to create a stake_requests table in the database, to create a new entry (stake request) and retrieve stake request by stake request' hash.

StakeRequestRepository class is covered by unit tests.
DatabaseWrapper class does not have unit tests, however, functions are mostly tested through StakeRequestRepository unit test. We should think what kind of tests do we want for DatabaseWrapper class.

DatabaseWrapper is documented.
StakeRequestRepository class is missing documentation.
