### ISSUE TITLE
Implement an anchor service.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#59]
Implement an anchor service (to handle the state root commit).

- nudge anchor service (chain Id)
- this will nudge the gateway service.
- Identifies the messages that were waiting for the state root commit.

**Comment by sarvesh-ost** [comment]
We have already implemented prove gateway service which proves gateway if there is any pending messages in PR #90. 
With prove gateway service, there is no need of anchor service.

Definition of done for this ticket: 
1. Implement origin anchor handler.
2. Persist state root and block height in auxiliary chain table if higher block is received.
