### ISSUE TITLE
Commander: Implement facilitator commands

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#6]
These are the commands that can be used to run the facilitators.

The proposed command is as given below, the implementer can improve this.

- [ ] **Facilitator command**.

```
./facilitator  --mosaic-config <mosaic_config_file_path> --facilitator-config <facilitator_config_file_path> --chain-id <chain-id>

```

- The facilitator can be started by `./facilitator`.
- `mosaic_config_file_path` is the path for the `mosaic.json` file. 
- `facilitator_config_file_path` is the path for the `facilitator.json` file. 
- `chain-id` must be the value of the chainid to be started.
- If the config path is not provided then the default path is used.
    - `$HOMEDIR/.mosaic/ethereum.json`
    - `$HOMEDIR/.mosaic/ropsten.json`
    - `$HOMEDIR/.mosaic/<chain-id>/facilitator.json`
- Facilitation must be done for one auxiliary chain.
- <strike>Password will be taken in interactive mode</strike>
- <strike>DB [Chain Id => unique key]</strike>
<br/>

- [ ] **Help command**.
```
./facilitator --help

```
- This command provides help for the facilitator command.

**Comment by deepesh-kn** [comment]
In the future, we can think of using anchor address instead of chain id.

**Comment by abhayks1** [comment]
chain-id on the command line is not needed since a facilitator will run for an origin-aux pair.
cc: @deepesh-kn

**Comment by deepesh-kn** [comment]
> chain-id on the command line is not needed since a facilitator will run for an origin-aux pair.
> cc: @deepesh-kn

This can be implemented in the following way
- `./facilitator   --facilitator-config <facilitator_config_file_path>`
Facilitator config already has the origin chain id and aux chain id. using the origin chain id we can get the mosaic config from the default location.

- `./facilitator   --origin-chain <origin_chain> --aux-chain <aux_chain_id>`
In this case, we have both chain ids, we can get the mosaic config and facilitator config from the default location.

In both the case ` --mosaic-config <mosaic_config_file_path>` can be optional.
