### ISSUE TITLE
Implement confirm stake intent service

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#61]
Implement confirm stake intent service

- Called from transaction handler when the gateway is proven.
- For the given gateway address get all the confirmable messages (of all types)
- Perform confirm stake intent for each message of type StakeAndMint.

**Comment by abhayks1** [comment]
Moving it to Backlog as didn't make any progress here and started working on another ticket #86

**Comment by abhayks1** [comment]
Moving it to parking lot as the ticket has dependencies on Issue #99
