### ISSUE TITLE
Graph node subscriptions should be incremental

### ISSUE THREAD

**Issue by abhayks1** [OpenST/facilitator#71]
Subscriptions with graph is working fine. 
The only issue is every time an entity matches it returns all the matching entity which as time passes becomes huge.
We only need the incremental matching entity data not all matching entity. 

The ticket is about exploring and handling this in code

Find below the gist link for the code: https://gist.github.com/abhayks1/68969d2e29a77585894369f99f037b73

**Comment by abhayks1** [comment]
Below graph query can be used for the incremental susbcriptions:
```
query {
  stakeRequesteds(first:100, orderDirection: desc, where: {blockNumber_gt: $blockNumber}) {
    id
    amount
    gasPrice
    gasLimit
    staker
    gateway
    stakeRequestHash
    nonce
    beneficiary
    blockNumber
  }
}
```
$blockNumber: (last processed block number) -1

**Comment by puneet-khushwani-eth** [comment]
I guess as we are working on #86, we wouldn't need this ticket any longer. 
@abhayks1 @deepesh-kn views please.

**Comment by deepesh-kn** [comment]
Closing this ticket as its already handled in https://github.com/OpenST/facilitator/pull/94
