### ISSUE TITLE
Config: Validate the mosaic-config content

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#8]
This is an implementation ticket. The actual implementation may vary as we start working on it.
Please check #2 first for any updates in params.

The `mosiac-config` file provided must be verified before we start the facilitator. 

Implement the function to validate the mosaic-config.
- Check #2 for the interface of the function.
- Validate if `mosaic-config` contains all the (mandatory and facilitator) params required for facilitation against mosaic schema, [see schema mosaic-chains #44](https://github.com/OpenST/mosaic-chains/issues/44)
    - Composer address
    - Gateway address 
    - Identify more.
- use npm tool to match against schema
- ~Assert the address from the chain.~
- Save the config in the variable (Implementor can decide the details)

**Comment by benjaminbollen** [comment]
close this ticket in favor of moving all validation into mosaic-chains
1. mosaic chains should have two steps of validation a) against the schema, b) the values against the chain contracts
2. publish mosaic chains as npm (TODO create ticket)
3. use mosaic chains npm here to assert validity of config agains schema
