### ISSUE TITLE
Create a new table that keeps track of the last processed entity.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/facilitator#85]
The facilitator gets the entities from the graph node.

The subscription to graph node returns overlapping entities. There should be a way to determine the processed entity and get only the unprocessed entity from the graph node. One way to handle is to use the `uts` updated timestamp.

Create a new table that keeps the track of the updated time stamp of each entity. This table will be updated once the entities are received by the transaction handler.

This table will be used to prepare the graph node query based on the updated timestamp.

**Comment by pgev** [comment]
@deepesh-kn should we rather let each repository to handle this. Each repository `create` function can silently ignore an entry if it exists (by primary key). What do you think?

**Comment by deepesh-kn** [comment]
> @deepesh-kn should we rather let each repository to handle this. Each repository `create` function can silently ignore an entry if it exists (by primary key). What do you think?

repositories will not have the information obout the entities from graph node. Example the StakeIntentDeclared, StakeIntentConfirmed, StakeProgressed, MintProgressed,... all will be in `message`. So it will require to save the `uts` for all types, so its a seperate table.
